server:
  servlet:
    context-path: /
  port: 9080
  compression:
    mime-types:
      - application/json

spring:
  profiles:
    active: test
  main:
    allow-bean-definition-overriding: true
  application:
    name: cartoes-ms